const getLegalInfoText = ({title}) => {
  switch (title) {
    case 'Termos de uso do serviço':
      return `A Terapia.app tem como propósito fornecer informações e ferramentas para ajudar você a ter uma vida saudável. Assim, apresentamos aqui os nossos Termos de Uso: um contrato ("Acordo") entre você (o Usuário) e nós (a empresa "Terapia.app"). Neste Termos de Uso descrevemos os serviços que oferecemos a você e as condições para uso do nosso Aplicativo móvel. Este é um documento legal e, por isso, parte da linguagem inclui termos jurídicos, mas tentamos deixá-lo o mais claro possível. Estes termos são tão importantes que não podemos fornecer nossos serviços e produtos a você sem antes obter seu aceite. Ao utilizar o aplicativo, você concorda com estes termos. Se você não concorda com estes Termos, você não pode usar nem acessar os nossos Serviços. Periodicamente atualizamos estes termos, por razões legais ou pelo uso de novas tecnologias e funcionalidades que entendermos necessárias.`;

    case 'Condições gerais':
      return `   "Acordo" refere-se a estes Termos de uso dos serviços oferecidos do nosso Aplicativo móvel (Site e/ou Aplicativo), e a todos os materiais mencionados ou vinculados por este documento. "Terapia.app" refere-se ao aplicativo software desenvolvido para ser instalado em um dispositivo eletrônico móvel, como telefone celular, e que disponibiliza o acesso ao conteúdo gratuito após adquirir um código de ativação fornecido por algum de nossos parceiros. "Terapia.app" refere-se ao serviço disponibilizado através do Aplicativo, cuja função é conectar usuários com profissionais das áreas de saúde, como Psicólogos e Terapeutas Complementares. O app coloca à disposição dos usuários consultas e sessões online. *Importante: A Terapia.app está disponível 24 horas por dia / 7 dias por semana para atendimentos, recebimento e respostas de dúvidas dos Usuários através de chats,  telefone, email e vídeo-chamadas.  "Conteúdo" são as informações, textos, pushs, notificações, imagens e/ou outros trabalhos que você vê, ouve ou assiste no site Terapia.app. "Conteúdo Gratuito" significa: Todo conteúdo audiovisual e ferramentas tecnológicas que possam ser acessadas a partir do momento que você está dentro do app, logo após ser inserido o código de ativação do aplicativo .`;

    case 'TerapiaApp':
      return `O nosso app é projetado para oferecer serviços terapêuticos e psicoterapêuticos, entretanto, não substitui (se for o caso), a relação entre você e seu médico ou outros profissionais de saúde que o acompanhem pessoal e presencialmente. Procure sempre consultar seu médico ou outro profissional de saúde qualificado quando tiver qualquer dúvida relacionada a uma condição médica. IMPORTANTE: A TERAPIA.APP NÃO É MONITORADO DE MANEIRA CONTÍNUA, PORTANTO NUNCA DESCONSIDERE O CONSELHO DE UM PROFISSIONAL NEM DEMORE A BUSCAR ATENDIMENTO MÉDICO QUANDO NECESSÁRIO. NUNCA UTILIZE A TERAPIA.APP PARA ABORDAR UMA EMERGÊNCIA MÉDICA. EM CASO DE EMÊRGÊNCIA, DISQUE 191 OU O NÚMERO DE EMERGÊNCIA DO SEU PLANO DE SAÚDE.`;

    case 'Declaração de uso':
      return `A Terapia.app não será responsável por qualquer dano decorrente do uso, mau uso ou da impossibilidade de uso do app e as informações nele contidas. A Terapia.app e seus especialistas, licenciadores e fornecedores não fazem nenhuma recomendação quanto à adequação, confiabilidade, disponibilidade, pontualidade, segurança ou precisão do conteúdo para qualquer finalidade, no limite máximo permitido pela legislação aplicável. Todas essas informações, softwares, produtos, serviços e gráficos relacionados são fornecidos “como estão”, sem garantia de qualquer espécie. A Terapia.app e seus especialistas, licenciadores e fornecedores se isentam de todas as garantias e condições relacionadas ao site e ao conteúdo, incluindo todas as garantias e condições implícitas de comercialização, adequação a um determinado fim, título e não-infração. Nenhum conselho ou informação, oral ou escrita, obtidos da Terapia.app deve, de maneira alguma, criar qualquer garantia não declarada expressa e explicitamente neste acordo. A responsabilidade dos atendimentos está rigorosamente ligada a cada profissional e ao seu registro de classe. Até ao limite máximo permitido por lei, em hipótese alguma A Terapia.app e seus provedores de serviços, licenciados ou fornecedores serão responsabilizados por quaisquer danos diretos, indiretos, punitivos, incidentais, especiais, consequentes, exemplares ou outros tipos de danos, incluindo, entre outros, danos por cobertura ou perda de uso, dados, receita ou lucros, decorrentes de ou de alguma forma relacionados ao uso ou desempenho do site, com o atraso ou a incapacidade de usar o site, ou por qualquer conteúdo, ou decorrente do uso do site, seja com base em contrato, negligência, responsabilidade objetiva, falta de qualquer recurso para atingir sua finalidade essencial, mesmo que A Terapia.app ou qualquer fornecedor da A Terapia.app tenha sido avisado da possibilidade de danos. Pelo fato de alguns estados/jurisdições não permitirem a exclusão ou a limitação de responsabilidade por danos consequentes ou incidentais, a limitação acima pode não se aplicar a você. Se, não obstante quaisquer outras disposições do presente acordo, for determinado que a A Terapia.app deva assumir qualquer responsabilidade a você ou a um terceiro por qualquer perda, dano ou prejuízo, você concorda que a responsabilidade total da A Terapia.app e de seus funcionários, diretores, gerentes, coligadas, agentes, fornecedores, prestadores de serviços, licenciadores ou fornecedores deve, em todos os casos, ser limitada a 1.000 reais. `;

    case 'Segurança de armazenamento de dados e política de privacidade confidencialidade das informações e atendimento dos usuários':
      return `A Terapia.app adotou uma Política de Privacidade, acessível no aplicativo, que pode ser modificada por nós de tempos em tempos. A Política de Privacidade irá reger qualquer divulgação ou uso de suas informações pessoais e as suas informações pessoais de saúde. Usando A Terapia.app, você declara que leu, compreendeu e concordou com os termos de tal Política de Privacidade.`;

    case 'Assinatura':
      return `Você concorda em ser o único usuário autorizado de sua conta. Você é responsável por manter a confidencialidade de qualquer número de senha e conta fornecida para acessar A Terapia.app. Você é totalmente responsável por todas as atividades que ocorram sob sua senha ou conta, incluindo a segurança do seu dispositivo móvel. Você concorda em notificar imediatamente a A Terapia.app qualquer uso não autorizado de sua senha ou conta ou qualquer outra violação de segurança. A Terapia.app não tem controle sobre o uso de nenhuma conta e renuncia expressamente qualquer responsabilidade decorrente.`;

    case 'Disposições finais':
      return `Acordo integral. Estes Termos de Uso constituem o acordo integral entre as partes com relação ao objeto do mesmo. Nenhuma renúncia por parte da Terapia.app de qualquer violação ou incumprimento estabelecida no presente será interpretada como uma renúncia de qualquer violação ou incumprimento precedente ou subsequente. b. Validade das cláusulas. Se alguma declaração destes Termos de uso for considerada inválida ou inaplicável, a declaração inválida ou inaplicável não afetará as outras cláusulas destes Termos de uso, os quais permanecerão em pleno vigor e efeito. c. Legislação Aplicável e Eleição de Foro. Todas e quaisquer disputas relacionadas a estes Termos de uso, à Política de Privacidade da Terapia.app, ao seu uso do Site ou do Aplicativo e de qualquer outro conteúdo da Terapia.app são regidos por e serão interpretados de acordo com as leis brasileiras, desconsiderando quaisquer conflitos entre cláusulas legais. Você concorda com a jurisdição exclusiva do foro da Comarca de Jundiaí, SP, Brasil, para qualquer disputa derivada ou relacionada a estes Termos de uso, à Política de privacidade da Terapia.app, ao seu uso do Site, Aplicativo e de qualquer outro website ou conteúdo da Terapia.app `;

    default:
  }
};

export default getLegalInfoText;
